server:
  port: 8080

spring:
    application:
        name: reactive-spring-boot
    # Reactive R2DBC configuration for PostgreSQL.
    r2dbc:
        url: r2dbc:postgresql://localhost:5532/db-postgresql
        username: admin
        password: admin

    # Kafka configuration used by our reactive components.
    kafka:
        bootstrap-servers: localhost:9092

        consumer:
            # Consumer group for the Kafka consumer.
            group-id: person-consumer-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                # Tells the JsonDeserializer which target type to convert to.
                spring.json.value.default.type: com.example.demo.dto.PersonDTO

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
    level:
        root: INFO
        com.example.demo: DEBUG
